version: '3'
services:
  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
  shastic_challenge:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    links:
      - mysql
      - api
    volumes:
      - ./client:/app
    stdin_open: true
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: 'pass'
      BUNDLE_IGNORE_MESSAGES: 0
  mysql:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    command: [mysqld, --character-set-server=utf8, --collation-server=utf8_unicode_ci]
    ports:
      - 3306:3306
    volumes:
      - ./:/app
    environment:
      MYSQL_ROOT_PASSWORD: 'pass'
