default: &default
  adapter: mysql2
  encoding: utf8
  host: mysql
  username: root
  password: pass

development:
  <<: *default
  database: api_development

test:
  <<: *default
  database: api_test

production:
  <<: *default
  database: api_production
