default: &default
  adapter: mysql2
  encoding: utf8
  timeout:  1000
  host:     <%= ENV.fetch("DB_HOST") { "mysql" } %>
  username: <%= ENV.fetch("DB_USER") { "root" } %>
  password: <%= ENV.fetch("DB_PASS") { "pass" } %>

development:
  <<: *default
  database: api_development

test:
  <<: *default
  database: api_test

production:
  <<: *default
  database: api_production
